config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, path: 'users'
  resources :users do
    resources :user_flags
  end
  resources :comments, path: "/greddit" do
    collection do
      get 'root_new'
      post 'root_new', to: "comments#create_root"
    end
    member do
      get 'predestroy'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :projects
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :parent,  class_name: "Comment", optional: true, foreign_key: 'parent_id'
  has_many   :replies, class_name: "Comment", dependent: :destroy
  belongs_to :user
  validates :title, presence: true, length: { minimum: 5 }
  validates :content, presence: true, length: { minimum: 2 }
  def nest_level
    nest_level = 1
    comment = self
    while comment.comment_id do
      comment = Comment.find(comment.comment_id)
      nest_level = nest_level + 1
    end
    return nest_level
  end
end

app/controllers/comments_controller.rb
require 'tree_builder'
require 'markdown'

class CommentsController < ApplicationController

  before_action except: [:index, :show] do
    authenticate_user!
  end

  def create
    @root_comment = Comment.find comment_params[:comment_id]
    @comment = @root_comment.replies.create comment_params
    up = @comment
    while (up = Comment.find up.comment_id).comment_id
    end
    redirect_to( (url_for up) + "#" + @comment.id.to_s )
  end

  def create_root
    @comment = Comment.create comment_params
    redirect_to @comment
  end

  def index
    @comments = Comment.all.sort_by {|e| e.created_at}
    @comments = @comments.select { |item| !item.comment_id}
    @comments.reverse!
  end

  def show
    @comment = Comment.find(params[:id])
    @renderer = Redcarpet::Markdown.new(MarkdownRenderer, no_intra_emphasis: true, autolink: true, fenced_code_blocks: true, disable_indented_code_blocks: true)
    @tree = TreeBuilder.new(@comment)
    @tree.render
    @is_mod = check_user_flag :admin, :mod
  end

  def new
    respond_to do |format|
      format.html
      format.js
    end
    @comment = Comment.new
    @root_comment = Comment.find params[:comment_id]
  end

  def search

  end

  def root_new
    @comment = Comment.new
  end

  def edit
    respond_to do |format|
      format.html
      format.js
    end
    @comment = Comment.find(params[:comment_id])
  end

  def predestroy
    respond_to do |format|
      format.html
      format.js
    end
    @comment = Comment.find(params[:comment_id])
  end

  def update
    @comment = Comment.find(params[:comment_id])

    if @comment.update(comment_params)
      up = @comment
      unless up.comment_id
        redirect_to up
      else
        while (up = Comment.find up.comment_id).comment_id
        end
        redirect_to( (url_for up) + "#" + @comment.id.to_s )
      end
    else
      render 'edit'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    to_redirect = @comment.comment_id
    @comment.destroy
    if to_redirect
      up = Comment.find(to_redirect)
      while (up = Comment.find up.comment_id).comment_id
      end
      redirect_to up
    else
      redirect_to comments_path
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :content, :comment_id, :title)
  end
end

app/helpers/comments_helper.rb
require 'tree_builder'

module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class='comment'>
  <% lines = word_wrap(comment.content, line_width: 56).split("\n") %>
  <pre class="inline comment"><%= @tree.next %></pre><br>
  <pre class="inline comment"><%= @tree.next %></pre>
  <a id="<%= comment.id %>"></a>
  <span class="badge badge-dark">
    <%= name = comment.user.username %>
  </span>
  <span class="container">
    <%= lines.slice!(0)[0,56] %>
  </span>
  <% lines.each do |line| %>
  <br>
  <pre class="inline comment"><%= @tree.current %><%= " " * (name.size + 1) %><%= " " * (@tree.prev.size-@tree.current.size) %></pre>
  <span class="container">
    <%= line %>
  </span>
  <% end %>
  <br>
  <pre class="inline comment"><%= @tree.current %><%= " " * (name.size + 1) %><%= " " * (@tree.prev.size-@tree.current.size) %></pre>
  <%= render "comment_links", tree: @tree, comment: comment %>
  <br>
  <%puts @is_mod%>
  <pre class="inline comment"><%= @tree.current %></pre>
</div>
<%= render comment.replies if comment.replies.any? %>

app/views/comments/_comment_links.html.erb
<span class="container">
  <div id="modal-window-new" class="modal hide fade" role="dialog" aria-labelledby="new-comment-modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>
  <% if current_user %>
  <%= link_to 'Reply', new_comment_path(comment_id: comment.id, comment: comment),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window-new', 'class' => 'reply-link'}  %>
  <% else %>
  <span class="reply-link">(Log in to post & reply)</span>
  <% end %>
  <% if current_user and (@is_mod or comment.user.id == current_user.id) %>
  <%= link_to 'Edit', edit_comment_path(comment_id: tree.comment.id, comment_id: comment.id, comment: comment),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window-edit', 'class' => 'reply-link'}  %>
  <div id="modal-window-edit" class="modal hide fade" role="dialog" aria-labelledby="edit-comment-modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>
  <span> </span>
  <%= link_to 'Delete', predestroy_comment_path(comment_id: tree.comment.id, comment_id: comment.id, comment: comment),  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window-delete', 'class' => 'reply-link'}  %>
  <div id="modal-window-predestroy" class="modal hide fade" role="dialog" aria-labelledby="delete-comment-modal" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>
  <% end %>
</span>

app/views/comments/_edit.html.erb
<%= form_for @comment, url: comment_path(comment_id: @comment.id), action: "update" do |form| %>
<div class="modal-header">
  <h4 class="modal-title" id="new-comment-modal">Edit Comment</h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>
<div class="modal-body">
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content, value: @comment.content, style: "width: 100%;" %>
  </p>
</div>
<div class="modal-footer">
  <%= form.submit nil, class: "btn btn-primary" %><button class="btn btn-secondary" data-dismiss="modal">Cancel</button>
</div>
<% end %>

app/views/comments/_new.html.erb
<%= form_for @comment, url: comments_path, action: "create" do |form| %>
<div class="modal-header">
  <h4 class="modal-title" id="new-comment-modal">New Comment</h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>
<div class="modal-body">
  <%= form.label :content %><br>
  <%= form.text_area :content, style: "width: 100%;" %>
  <%= form.hidden_field :comment_id, value: @root_comment.id %>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.hidden_field :title, value: "Reply" %>
</div>
<div class="modal-footer">
  <%= form.submit nil, class: "btn btn-primary" %><button class="btn btn-secondary" data-dismiss="modal">Cancel</button>
</div>
<% end %>

app/views/comments/_predestroy.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="predestroy-comment-modal">Delete Comment</h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>
<div class="modal-body">
  <p>
    Are you sure you want to delete "<%= @comment.content %>"?
  </p>
</div>
<div class="modal-footer">
  <%= button_to "Delete", comment_path(id: @comment.id), class: "btn btn-primary", method: :delete %><button class="btn btn-secondary" data-dismiss="modal">Cancel</button>
</div>

app/views/comments/edit.js.erb
$("#modal-window-edit").find(".modal-content").html("<%= j (render 'edit') %>");
$("#modal-window-edit").modal();

app/views/comments/index.html.erb
<h1>Threads</h1><%= link_to "+ New Thread", root_new_comments_path %>

<script>

  jQuery(document).ready(function($) {
    $(".clickable-row").click(function() {
      window.location = $(this).data("href");
    });
  });

</script>

<table class="table table-striped table-hover table-bordered align-items-middle">
  <thead class="thead thead-dark">
    <tr>
      <th colspan="1">User</th>
      <th>Thread</th>
      <th>Replies</th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
    <tr class='clickable-row' data-href='/greddit/<%= comment.id %>/'>
      <!-- <td><img src="<= comment.user.imagelink %>" height="42" width="42"></td> -->
      <td><div class="container-fluid"><b><%= comment.user.username %></b></div></td>
      <td><div class="container-fluid"><%= comment.title %></div></td>
      <td><div class="container-fluid"><%= comment.replies.size %></div></td>
    </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Back', "/" %>

app/views/comments/new.js.erb
$("#modal-window-new").find(".modal-content").html("<%= j (render 'new') %>");
$("#modal-window-new").modal();

app/views/comments/predestroy.js.erb
$("#modal-window-predestroy").find(".modal-content").html("<%= j (render 'predestroy') %>");
$("#modal-window-predestroy").modal();

app/views/comments/root_new.html.erb
<body>
  <h1>New Thread</h1>
  <%= form_with scope: :comment, url: root_new_comments_path, action: :create_root, local: true do |form| %>

  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@comment.errors.count, "error") %> prohibited
        this thread from being saved:
      </h2>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <br>
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content, style: "width: 100%;" %>
  </p>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <br>
  <p>
    <%= form.submit %>
  </p>

  <% end %>
  <br>
  <%= link_to 'Cancel', controller: 'comments' %>
</body>

app/views/comments/show.html.erb
<!-- <h3>< @comment.title %></h3> -->
<!-- <hr> -->
<span class="badge badge-info">
  <%= @comment.user.username %>
</span>
<span class="container">
  <%= sanitize @renderer.render(@comment.content) %>
</span>
<br>
<%= render "comment_links", tree: @tree, comment: @comment, is_mod: @is_mod %>
<hr>
<%= render @comment.replies %>
<hr>

<%= link_to 'Back', comments_path %>