config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, path: 'users'
  resources :users do
    resources :user_flags
  end
  resources :comments, path: "/greddit" do
    collection do
      get 'root_new'
      post 'root_new', to: "comments#create_root"
    end
    member do
      get 'predestroy'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :projects
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
  validates :text, presence: true, length: { minimum: 30 }
  validates :imagelink, presence: true, length: { minimum: 5 }
end

app/controllers/projects_controller.rb
require "markdown"

class ProjectsController < ApplicationController

  before_action except: [:index, :show] do
    authenticate_user!
    user_flag "admin"
  end

  def index
    @projects = Project.all.sort_by {|project| project.catagory}
  end

  def show
    @project = Project.find(params[:id])
    @renderer = Redcarpet::Markdown.new(MarkdownRenderer, no_intra_emphasis: true, autolink: true, fenced_code_blocks: true, disable_indented_code_blocks: true)
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to @project
    else
      render 'edit'
    end
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project
    else
      render 'new'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:title, :text, :date, :imagelink)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<h1>Edit project</h1>

<%= form_with(model: @project, local: true) do |form| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %> prohibited
        this project from being saved:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text, size: "100x12" %>
  </p>

  <p>
    <%= form.label :date %><br>
    <%= form.text_field :date %>
  </p>

  <p>
    <%= form.label :imagelink %><br>
    <%= form.text_field :imagelink %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Catagory</th>
    <th>Image</th>
    <th></th>
  </tr>

  <% @projects.each do |project| %>
  <tr>
    <td><div class="container"><%= project.title %></div></td>
    <td><div class="container"><b><%= project.catagory %></b></div></td>
    <td><img src="<%= project.imagelink %>" height="42" width="42"></td>
    <td><%= link_to 'Show', project_path(project) %></td>
  </tr>
  <% end %>

  <tr>
    <td></td>
    <td></td>
    <td><%= link_to 'Back', "/" %></td>
  </tr>
</table>

app/views/projects/new.html.erb
<body>
  <h1>New Project</h1>
  <%= form_with scope: :project, url: projects_path, local: true do |form| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %> prohibited
        this project from being saved:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text, size: "100x12" %>
  </p>

  <p>
    <%= form.label :date %><br>
    <%= form.text_field :date %>
  </p>

  <p>
    <%= form.label :imagelink %><br>
    <%= form.text_field :imagelink %>
  </p>

  <p>
    <%= form.label :catagory %><br>
    <%= form.text_field :catagory %>
  </p>

  <p>
    <%= form.submit %>
  </p>

  <% end %>
  <%= link_to 'Cancel', controller: 'projects' %>
</body>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<hr>
<br>
<img src="<%= @project.imagelink %>" alt="Project Image" width="400">
<br>
<br>
<hr>
<br>
<p>
  <strong>Info:</strong><br>
  <%= @renderer.render(@project.text).html_safe %>
</p>
<br>
<hr>
<br>
<p>
  <strong>Date completed:</strong><br>
  <%= @project.date %>
</p>
<br>
<hr>
<br>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>