config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, path: 'users'
  resources :users do
    resources :user_flags
  end
  resources :comments, path: "/greddit" do
    collection do
      get 'root_new'
      post 'root_new', to: "comments#create_root"
    end
    member do
      get 'predestroy'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :projects
end

app/models/user_flag.rb
class UserFlag < ApplicationRecord

  belongs_to :user

end

app/controllers/user_flags_controller.rb
class UserFlagsController < ApplicationController
  before_action :authenticate_user!
  before_action do
    user_flag "admin"
  end
  before_action :set_user_flag, only: [:show, :edit, :update, :destroy]

  # GET /user_flags
  # GET /user_flags.json
  def index
    @user_flags = UserFlag.all
  end

  # GET /user_flags/1
  # GET /user_flags/1.json
  def show
  end

  # GET /user_flags/new
  def new
    @user_flag = UserFlag.new
  end

  # GET /user_flags/1/edit
  def edit
  end

  # POST /user_flags
  # POST /user_flags.json
  def create
    @user_flag = UserFlag.new(user_flag_params)

    respond_to do |format|
      if @user_flag.save
        format.html { redirect_to @user_flag, notice: 'User flag was successfully created.' }
        format.json { render :show, status: :created, location: @user_flag }
      else
        format.html { render :new }
        format.json { render json: @user_flag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_flags/1
  # PATCH/PUT /user_flags/1.json
  def update
    respond_to do |format|
      if @user_flag.update(user_flag_params)
        format.html { redirect_to @user_flag, notice: 'User flag was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_flag }
      else
        format.html { render :edit }
        format.json { render json: @user_flag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_flags/1
  # DELETE /user_flags/1.json
  def destroy
    @user_flag.destroy
    respond_to do |format|
      format.html { redirect_to user_flags_url, notice: 'User flag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_flag
      @user_flag = UserFlag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_flag_params
      params.require(:user_flag).permit(:user, :content)
    end
end

app/helpers/user_flags_helper.rb
module UserFlagsHelper
end

app/views/user_flags/_form.html.erb
<%= form_with(model: user_flag, local: true) do |form| %>
  <% if user_flag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_flag.errors.count, "error") %> prohibited this user_flag from being saved:</h2>

      <ul>
      <% user_flag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user %>
    <%= form.text_field :user %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_flags/edit.html.erb
<h1>Editing User Flag</h1>

<%= render 'form', user_flag: @user_flag %>

<%= link_to 'Show', @user_flag %> |
<%= link_to 'Back', user_flags_path %>

app/views/user_flags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Flags</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_flags.each do |user_flag| %>
      <tr>
        <td><%= user_flag.user %></td>
        <td><%= user_flag.content %></td>
        <td><%= link_to 'Show', user_flag %></td>
        <td><%= link_to 'Edit', edit_user_flag_path(user_flag) %></td>
        <td><%= link_to 'Destroy', user_flag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Flag', new_user_flag_path %>

app/views/user_flags/new.html.erb
<h1>New User Flag</h1>

<%= render 'form', user_flag: @user_flag %>

<%= link_to 'Back', user_flags_path %>

app/views/user_flags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_flag.user %>
</p>

<p>
  <strong>Content:</strong>
  <%= @user_flag.content %>
</p>

<%= link_to 'Edit', edit_user_flag_path(@user_flag) %> |
<%= link_to 'Back', user_flags_path %>